### ISSUE TITLE
Cannot test Commdn groups with click.testing.CliRunner

### ISSUE THREAD

**Issue by kissgyorgy** [mitsuhiko/click#267]
When calling `CliRunner.invoke()` on a subcommand with parameters and extra arguments, the extra arguments don't get passed because those are not handled by `Command` and `BaseCommand`.

There is a [call to Command.__ini__ with extra args in Multicommand](https://github.com/mitsuhiko/click/blob/master/click/core.py#L868) but [Command doesn't handle the passed in optional keywords](https://github.com/mitsuhiko/click/blob/master/click/core.py#L689).

I don't know how to solve this.

Here is the first call with runner.invoke which causes the problem:
https://github.com/mitsuhiko/click/blob/master/click/testing.py#L257

**Comment by untitaker** [comment]
You're supposed to do

    runner.invoke(cli.main, ['download', '2014', '11', '10', '--config', 'config.json'])

Please comment if this doesn't help you.

**Comment by mesuutt** [comment]
I have a similar problem:

I have a command group which get a `--config` paramter shown as below:

```python
click.group()
@click.option(
    '--config', '-c',
    type=click.Path(),
    help='Config file path'
)
@click.pass_context
def cli(context, config_file,  **kwargs):
    ....
```

And sub commands of group:

```python
@cli.command(name='ls')
@click.pass_context
def list_files(context):
   ....
```

I am invoking `ls` command with `--config` option from command line shows as below and everything works expected:
`python app.py --config ~/.myconfig ls`

Now I want to write test for my commands but I don't know how to give `--config` option 
to `CliRunner`

I tried as below but not worked for me:
```python
runner = CliRunner()
result = runner.invoke(list_files, ['--config', config_file])
```  
I think CliRunner getting `--config` option as option of `ls` command instead of group and  invoking `ls` command as `app.py ls --config ~/.myconfig` instead of `app.py --config ~/.myconfig ls`.

How can I solve this?

**Comment by geowurster** [comment]
@mesuutt Try this:

```python
result = runner.invoke(cli, ['--config', config_file, 'ls'])
```

Essentially you have to tell `CliRunner()` to run the main CLI group and then pass in a full list of flags, including the name of the subcommand you actually want to run.

**Comment by mesuutt** [comment]
Thanks @geowurster. This solved the problem :+1:

**Comment by HalfDeadPie** [comment]
`@click.group('yum')
@click.option('--config', '-c', default='config.cfg',
              help='Path of the auth config file.')
@click.option('--username', '-u', envvar='IG_USERNAME',
              help='Instagram username')
@click.option('--password', '-p', envvar='IG_PASSWORD',
              help='Instagram password')
@click.pass_context
def cli(ctx, config, username, password):
...

@cli.command()
@click.option('--id', '-i', help='XP Gain from the photo with ID')
@click.pass_context
def gain(ctx, id):
....
`

I would like to test this, without using the options or arguments. Just "yum gain"
Can anyone help me please?

` runner = CliRunner()
    result = runner.invoke(cli, ['gain'])`

doesn't work :(
