### ISSUE TITLE
Opening a File for reading with atomic=True truncates file

### ISSUE THREAD

**Issue by mdklatt** [mitsuhiko/click#357]
Python 2.7.1 (OS X 10.7), Click 4.0

    import click

    @click.command()
    @click.argument("file", type=click.File(mode="r+", atomic=True))
    def clobber(file):
        # This should be a read-only operation, but the file is empty on exit.
        # File is already empty by the time read() is called on it.
        click.echo(file.read())
        return

    if __name__ == "__main__":
        clobber()

My use case is opening a file that needs to be read from and then optionally written to. However, opening the file with mode `r` or `r+` truncates the file for `atomic=True`. What is the best way to update a file? 

In any case, having your file clobbered with mode `r` is certainly not expected.

**Comment by untitaker** [comment]
Atomic file writes work by creating a temporary file that is moved over the original one, since `rename` is atomic. Your file appears to be empty because the temporary file really is, at the end of your CLI app the original file is replaced.

Because atomic file writes work the way they do, you can't "just modify a file in-place" without copying the whole file to a temporary location. But I think if click started doing that implictly for the `+`-modes, I think we'd hide the performance penalties that come with copying the whole file. Furthermore none of this would be really atomic anymore. I strongly suspect that you're using the `atomic=True` option in a case where it can't be even applied.

There is some usability bug in click. I'm not sure how to solve it. Perhaps we should disallow any other mode than `w` if `atomic=True` is used.

**Comment by mdklatt** [comment]
I've had to roll my own atomic file before, and I resolved this issue by not bothering to create/copy the temporary file if the mode was read-only. Of course, that doesn't solve the "r+" case.  Perhaps this could be tied to `lazy=True` so that the temporary file is only created on write, not read.

**Comment by untitaker** [comment]
>not bothering to create/copy the temporary file if the mode was read-only

I don't think that's a good behavior for Click, since this pretty much defeats the purpose of `atomic=True`.

>Perhaps this could be tied to lazy=True so that the temporary file is only created on write, not read.

So `read` would actually use a different fp than `write` does?

**Comment by mdklatt** [comment]
> So read would actually use a different fp than write does?

Hmm. In this case, I guess that it would. I agree the current behavior is probably the best way to handle this, but, to prevent surprised, the documentation should mention that `atomic=True` should not be mixed with reading.

**Comment by untitaker** [comment]
>the documentation should mention that atomic=True should not be mixed with reading.

Would you be okay with preventing that edgecase in the code itself (by raising a clear error message)? Is there a situation where the user actually wants to pass both `r+` and `atomic=True` if they know what they are doing?

**Comment by mdklatt** [comment]
> Would you be okay with preventing that edgecase in the code itself (by raising a clear error message)?

I think that's fine.

>  Is there a situation where the user actually wants to pass both r+ and atomic=True if they know what they are doing?

For me, `r+` means the file doesn't get modified unless you write to it, which is not the case here. The way it works now, `atomic=True` really gives you `w+` semantics.

**Comment by untitaker** [comment]
I've added some error messages to master, but I think this might as well be fixed by https://github.com/mitsuhiko/click/issues/320
