### ISSUE TITLE
Feature Request: default-value only if option set without argument

### ISSUE THREAD

**Issue by tuxlife** [mitsuhiko/click#370]
It would be very nice, if the default value only set, if the option put without argument.

```python
def test_magicdefault(runner):
    @click.command()
    @click.option('--foo', magicdefault=5)
    def cmd(foo):
        click.echo(foo)

    result = runner.invoke(cmd, [])
    assert result.output == 'None\n'

    result = runner.invoke(cmd, ['--foo'])
    assert result.output == '5\n'

    result = runner.invoke(cmd, ['--foo', '42'])
    assert result.output == '42\n'
```

**Comment by untitaker** [comment]
This would make options ambiguous because it's no longer clear whether the `5` in `-w 5` should be parsed as argument or as value for the `-w`-option. Even if we decide on some precedence-rule, this would be hard to learn for users.

**Comment by tuxlife** [comment]
That's definitely a good point.

But for a watch-option, is a possible default value better.

The solution from mysql is one way for the 'hould be parsed as argument or as value'-Problem:
```
-p => Ask for a password with a promt
-pxzy => use as password xzy
-p xyz => Ask for a password with a promt and xyz is the next option
```

But this is not compatible with the previous version.

**Comment by untitaker** [comment]
Yes, mysql did decide on something, but I wouldn't be able to figure out the difference between `-pxyz` and `-p xyz` without learning mysql's own syntax. I'd even call this a bad design decision because it will lead to hard-to-find bugs if `xyz` is parsed as argument.

As said, consider making `-w` a flag and add a new parameter `--watch-timeout` (or whatever the number represents). In fact I'd urge you do so. I guarantee you that this will result in an easier-to-learn CLI.

**Comment by tuxlife** [comment]
:thumbsup:

I think you're right.
