### ISSUE TITLE
Chain doesn't work with nested groups

### ISSUE THREAD

**Issue by mlenzen** [mitsuhiko/click#415]
If a group has chain set as true, the commands of a sub-group can't be executed.

Minimal exmaple cli.py

    import click
    
    @click.group(chain=True)
    def cli():
        pass
    
    @cli.group()
    def gp():
        pass
    
    @gp.command()
    def cmd():
        pass
    
    cli()

Then

    $ python cli.py gp cmd
    Usage: cli.py [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...
    
    Error: No such command "cmd".

Maybe this isn't resolvable, but the docs say "When using multi command chaining you can only have one command (the last) use nargs=-1 on an argument. Other than that there are no restrictions on how they work." at http://click.pocoo.org/5/commands/#multi-command-chaining

Using Python 3.4.3 and Click 5.1

**Comment by mitsuhiko** [comment]
This is actually something that cannot be supported given the guarantees subcommand invocations have.  Click now gives a proper error message when trying to do something like this instead of doing the unexpected thing.

**Comment by mitsuhiko** [comment]
It actually turns out that some of the guarantees that were given did not really make sense.  There were actually cases where the current behavior accidentally caused bugs as well.  So in Click 6 the following things are true:

* chain commands can nest
* if a chain command is below a chain comment it will eat up all arguments and returning to the outer chain is impossible
* optional arguments on a group are no longer supported.

**Comment by mitsuhiko** [comment]
For the changes see 0a2919f34fcbc635d8530b4c5b60bf119b2bcedb and earlier commits.
