### ISSUE TITLE
make Command.__call__ accept typed parameters

### ISSUE THREAD

**Issue by flying-sheep** [mitsuhiko/click#416]
a module that is at the same time CLI via `__main__` and importable shouldn’t contain a bunch of list-of-string APIs.

in order to avoid doing

```py
from my_module import do_stuff

do_stuff.callback(5)
```

i found myself doing this instead of using the decorators:

```py
if __name__ == '__main__':
	cli = click.Group(help=__doc__)
	
	def add_clc(name, fun, *params):
		cli.add_command(click.Command(name, {}, fun, list(params), inspect.getdoc(fun)))
	
	add_clc('do-stuff', do_stuff, 
		click.Argument(['foo'], type=INT),
	)
	
	cli()
```

it would be awesome if `Command.__call__` would validate and convert the parameters directly instead of expecting a list of strings.

**Comment by untitaker** [comment]
What you probably see as a workaround is IMO much better than relying on Click to pass the params through (since using your code as a library shouldn't require an understanding of Click's API).

Apart from that I'm not sure if it's even technically possible to do what you ask for, since arg validation probably has to happen way before e.g. the group's function body is called.

FWIW instead of instantiating Command explicitly you can also do:

    cli.command(...)(f)

On 28 August 2015 11:18:32 CEST, "Philipp A." <notifications@github.com> wrote:
>a module that is at the same time CLI via `__main__` and importable
>shouldn’t contain a bunch of list-of-string APIs.
>
>in order to avoid doing
>
>```py
>from my_module import do_stuff
>
>do_stuff.callback(5)
>```
>
>i found myself doing this instead of using the decorators:
>
>```py
>if __name__ == '__main__':
>	cli = click.Group(help=__doc__)
>	
>	def add_clc(name, fun, *args):
>		cli.add_command(click.Command(name, {}, fun, args, fun.__doc__))
>	
>	add_clc('do-stuff', do_stuff, 
>		click.Argument(['foo'], type=INT),
>	)
>	
>	cli()
>```
>
>it would be awesome if `Command.__call__` would validate and convert
>the parameters directly instead of expecting a list of strings.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/click/issues/416

-- 
Sent from my phone. Please excuse my brevity.

**Comment by flying-sheep** [comment]
> FWIW instead of instantiating Command explicitly you can also do
> 
>     cli.command(...)(f)

well, that would look silly when used with arguments:

```py
cli.command('do-stuff')(
    click.argument('foo', type=INT)(
        click.option('--bar', default=1)(
            do_stuff)))
```

and my gripe is that i like the decorator style, but there’s no easy form to proxy a function.

```py
@cli.command('do-stuff', help=inspect.getdoc(do_stuff))
@click.argument('foo', type=INT)
def do_stuff_cmd(foo):
    return do_stuff(foo)
```

this isn’t DRY and the manual `getdoc` is also annoying.

**Comment by untitaker** [comment]
You can use functools.wraps instead of inspect, and you can avoid the excessive indention by usage of variable assignments.

This really isn't something Click supports, because decorated commands are full of side effects which hardly makes for a good library API. You may be annoyed by the repetition, but it's actually a good thing to avoid conflating these two kinds of APIs.

On 29 August 2015 17:22:00 CEST, "Philipp A." <notifications@github.com> wrote:
>> FWIW instead of instantiating Command explicitly you can also do
>> 
>>     cli.command(...)(f)
>
>well, that would look silly when used with arguments:
>
>```py
>cli.command('do-stuff')(
>    click.argument('foo', type=INT)(
>        click.option('--bar', default=1)(
>            do_stuff)))
>```
>
>and my gripe is that i like the decorator style, but there’s no easy
>form to proxy a function.
>
>```py
>@cli.command('do-stuff', help=inspect.getdoc(do_stuff))
>@click.argument('foo', type=INT)
>def do_stuff_cmd(foo):
>    return do_stuff(foo)
>```
>
>this isn’t DRY and the manual `getdoc` is also annoying.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/click/issues/416#issuecomment-135998711

-- 
Sent from my phone. Please excuse my brevity.

**Comment by flying-sheep** [comment]
right now i have this kind of boilerplate:

```py
@cli.command('extract-barcodes')
...arguments
@wraps(extract_barcodes)
def extract_barcodes_cmd(accession, regex1, regex2, group_by, warnings):
	return extract_barcodes(accession, regex1, regex2, group_by, warnings)
```

not really happy with it. the last 3 lines are entirely redundant, but necessary to get decorator syntax.

**Comment by untitaker** [comment]
If that syntax makes you happy, good for you (although I personally find that this usage of decorators goes too far).

I'm not really opposed to adding shortcuts to improve usage of such cases, but the original proposal (overloading `Command.__call__`) is IMO not a good idea, even if possible.

**Comment by flying-sheep** [comment]
@`Command.__call__`: yeah, OK.

@decorator abuse: the only other way is to do

```py
@cli.command('do-stuff')
@cli.argument('foo')
def do_stuff_cmd(foo):
	...

do_stuff = do_stuff_cmd.callback
```

but that doesn’t match my intention to define the command line interface at one place
